CREATE DATABASE dacbotdb;

CREATE TABLE CALENDAR (
    ID SERIAL,
    YEAR_INTEGER INT,
    SEMESTER_INTEGER INT,
    ENTITY_STR VARCHAR(100),
    DESCRIPTION_STR VARCHAR(500),
    INITIAL_DATE DATE,
    END_DATE DATE,
    URI_STR VARCHAR(100)
);
