entities = {
    "feriado": "Feriado/Expediente Suspenso",
    "ferias_verao": "Férias de Verão",
    "sistema_de_recuperacao": "Sistema de Recuperação",
    "processo_seletivo_aberto": "Processo Seletivo Aberto",
    "colacao_grau": "Colação de Grau",
    "vestibular_unicamp": "Vestibular Unicamp",
    "catalogo_graduacao": "Catálogo dos Cursos de Graduação",
    "adequacao_matricula": "Adequação de Matrícula",
    "periodo_letivo": "Período Letivo",
    "relatorio_matricula_integralizacao": ["Relatórios de Matrícula e de Integralização Curricular", 'Relatório de Matrícula e Relatório de Integralização Curricular'],
    "alteracao_matricula": "Alteração de Matrícula",
    "estudante_especial": "Estudante Especial",
    "desistencia_disciplina": "Desistência de Matrícula em disciplina",
    "trancamento_matricula": "Trancamento de Matrícula (Semestre)",
    "teste_proficiencia": "Teste de Proficiência",
    "paa": "PAA",
    "avaliacao_curso": ["Avaliação e discussão dos cursos", "Avaliação e discussão de cursos"],
    "horarios": ["Horários", "Horário"],
    "carta_aceitacao": "Carta de Aceitação",
    "remanejamento_interno": "Remanejamento Interno",
    "semana_estudos": "Semana de Estudos",
    "media_frequencia": "Média e Frequência",
    "matricula_disciplina": "Matrícula em Disciplina",
    "aproveitamento_estudos": "Aproveitamento de Estudos",
    "exames": "Exames Finais",
    "sistema_recuperacao": "Sistema de Recuperação",
    "estudante_intercambista": "Estudante Intercambista",
    "congresso_iniciacao_cientifica": "Congresso de Iniciação Científica"
}